# Generated by Django 3.0.7 on 2020-06-05 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('cnpj', models.CharField(max_length=11, unique=True, verbose_name='CNPJ')),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Exame')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('funcao', models.CharField(max_length=50, verbose_name='Função')),
                ('sexo', models.CharField(choices=[('m', 'masculino'), ('f', 'feminino'), ('o', 'outros')], max_length=2, verbose_name='Sexo')),
                ('data_nasc', models.DateField(verbose_name='Data nascimento')),
                ('rg', models.IntegerField(unique=True, verbose_name='RG')),
                ('orgao_exp', models.CharField(max_length=5, verbose_name='Orgão Expedidor')),
                ('telefone', models.CharField(max_length=12, verbose_name='Telefone')),
                ('rua', models.CharField(max_length=80, verbose_name='Rua/Av./Logradouro')),
                ('numero', models.CharField(max_length=50, verbose_name='Numero/Bloco/Quadra')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=80, verbose_name='Cidade')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MTS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondonia'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=10, verbose_name='Estado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paciente.Empresa', verbose_name='Epresa')),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, max_length=500, verbose_name='Observações')),
                ('dt_exame', models.DateField(verbose_name='Data do exame')),
                ('dd_atendimento', models.DateTimeField(auto_now=True, verbose_name='Data de atendimento')),
                ('exame', models.ManyToManyField(to='paciente.Exame', verbose_name='Exame')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente', verbose_name='Paciente')),
            ],
        ),
    ]
