# Generated by Django 3.0.7 on 2020-06-05 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_auto_20200605_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='dt_exame',
        ),
    ]
