# Generated by Django 3.0.7 on 2020-06-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_remove_atendimento_dt_exame'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='laboratorio',
            field=models.CharField(default=1, max_length=60, verbose_name='Laboratorio / Empresa'),
            preserve_default=False,
        ),
    ]
